server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
# 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI5tCerw7PsyQf5upP2pQg
    keySecret: KpM5T2GGPoRsNl7M7nyzTkJThFiU9c
    bucketName: srb-file-202111-1